title: Tales Cunha
email: tvac@cin.ufpe.br
description: >-
  Backend Developer & CS Master's student at UFPE. Specializing in scalable systems,
  static analysis, and software quality.
baseurl: ""
url: "https://tales-cunha.github.io"

github_username: Tales-Cunha
linkedin_username: talesv-cunha

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - { platform: github, user: Tales-Cunha }
    - { platform: linkedin, user: talesv-cunha }

defaults:
  - scope:
      path: "pt"
    values:
      lang: pt
  - scope:
      path: ""
    values:
      lang: en
